#pragma once
/* ================================================================
 * lang_en.h  -  English strings (default)
 * ================================================================ */

/* --- Main loop --- */
#define MSG_TITLE           "=== ENIGMA Compressor ===\n"
#define MSG_HELP_DROP       "Drag files here or type a path manually.\n"
#define MSG_HELP_ENTER      "  [Enter]   = run encryption + log disguise\n"
#define MSG_HELP_RESTORE    "  1         = restore files from disguised log\n"
#define MSG_HELP_LIST       "  2         = show queue\n"
#define MSG_HELP_CLEAR      "  3         = clear queue\n"
#define MSG_HELP_EXIT       "  4         = exit\n\n"
#define MSG_PROMPT_CMD      "\n[1] Restore  [2] List  [3] Clear  [4] Exit\n"
#define MSG_QUEUE_EMPTY     "  (queue is empty)\n"
#define MSG_QUEUE_ENTRY     "  [%d] %s\n"
#define MSG_QUEUE_CLEARED   "  Queue cleared.\n"
#define MSG_ADDED           "  Added [%d]: %s\n"
#define ERR_QUEUE_FULL      "  [ERROR] Queue full (max %d).\n"
#define ERR_ALLOC_QUEUE     "  [ERROR] Memory allocation for path queue failed.\n"

/* --- Encryption (gabungkan_berkas) --- */
#define MSG_NO_VALID_FILES  "  (no valid files in queue)\n"
#define MSG_PROMPT_BASENAME "Output base name (blank = output): "
#define MSG_PROMPT_PNG_ENC  "Key PNG file (blank = %s_key.png): "
#define MSG_PROMPT_PASSWORD "XOR password (blank = no XOR): "
#define MSG_STEP1           "\n[STEP 1/6] Fetching seed...\n"
#define MSG_STEP2           "[STEP 2/6] Hiding seed in PNG LSB: %s\n"
#define MSG_STEP3           "[STEP 3/6] Initialising Enigma rotors...\n"
#define MSG_STEP4           "[STEP 4/6] Packing %d file(s) -> %s\n"
#define MSG_STEP5           "[STEP 5/6] Encrypting: %s -> %s\n"
#define MSG_STEP6           "[STEP 6/6] Disguising: %s -> %s_partNNN.log\n"
#define MSG_SEED            "[SEED] %s\n\n"
#define MSG_PNG_OK          "[PNG]   Seed hidden in: %s\n\n"
#define MSG_ENIGMA_READY    "[ENIGMA] Rotors ready.\n\n"
#define MSG_PACK_DONE       "[PACK]  Done: %s\n\n"
#define MSG_ENC_DONE        "[ENC]   Done: %s\n\n"
#define MSG_LOG_DONE        "[LOG]   Done: %d part(s).\n\n"
#define MSG_DONE_TITLE      "=== DONE ===\n"
#define MSG_DONE_LOG        "  Log  : %s_part001.log ... _part%03d.log\n"
#define MSG_DONE_KEY        "  Key  : %s  (keep it safe!)\n\n"
#define ERR_ALLOC_FILES     "  [ERROR] Memory allocation for file list failed.\n"
#define ERR_SEED            "  [ERROR] Failed to fetch seed from Wikipedia.\n\n"
#define ERR_PNG_SAVE        "  [ERROR] Failed to save seed to PNG.\n\n"
#define ERR_PACK            "  [ERROR] Packing failed.\n\n"
#define ERR_ENC             "  [ERROR] Encryption failed.\n\n"
#define ERR_LOG             "  [ERROR] Log disguise failed.\n\n"

/* --- Restore (pulihkan_berkas) --- */
#define MSG_PROMPT_LOG_PREFIX   "Input log prefix (e.g. output): "
#define MSG_PROMPT_OUT_ARCHIVE  "Output archive file (blank = hasil.engm): "
#define MSG_PROMPT_PNG_DEC      "Key PNG file (blank = %s_key.png): "
#define MSG_RESTORE_STEP0       "\n[STEP 0/3] Extracting seed from PNG LSB: %s\n"
#define MSG_RESTORE_STEP1       "[STEP 1/3] Restoring from log: %s_partNNN.log -> %s\n"
#define MSG_RESTORE_STEP2       "[STEP 2/3] Initialising Enigma rotors...\n"
#define MSG_RESTORE_STEP3       "[STEP 3/3] Decrypting: %s -> %s\n"
#define MSG_RESTORE_STEP4       "[STEP 4/4] Extracting archive: %s\n"
#define MSG_RESTORE_PNG_OK      "[PNG]  Seed extracted successfully.\n\n"
#define MSG_RESTORE_LOG_OK      "[LOG]  %lld bytes restored.\n\n"
#define MSG_RESTORE_DEC_OK      "[DEC]  Done: %s\n\n"
#define MSG_RESTORE_ARCHIVE_COUNT "[ARCHIVE] %u file(s) found.\n"
#define MSG_RESTORE_FILE_OK     "  [OK]  %-60s  %llu bytes\n"
#define MSG_RESTORE_DONE_TITLE  "\n=== DONE ===\n"
#define MSG_RESTORE_DONE        "  %u file(s) restored.\n\n"
#define ERR_PNG_EXTRACT         "  [ERROR] Failed to extract seed from PNG.\n\n"
#define ERR_LOG_RESTORE         "  [ERROR] Log restoration failed.\n\n"
#define ERR_DEC                 "  [ERROR] Decryption failed.\n\n"
#define ERR_OPEN_ARCHIVE        "  [ERROR] Cannot open archive.\n\n"
#define ERR_ALLOC_BUF           "  [ERROR] Memory allocation failed.\n\n"
#define ERR_READ_ARCHIVE        "  [ERROR] Failed to read archive.\n\n"
#define ERR_ALLOC_ENTRY         "  [ERROR] Memory allocation for entries failed.\n\n"
#define ERR_INVALID_ARCHIVE     "  [ERROR] Invalid archive or wrong seed.\n\n"
#define ERR_SKIP_FILE           "  [SKIP] %s (failed to open for writing)\n"
