#pragma once
/* ================================================================
 * lang_ja.h  -  日本語文字列
 * このファイルは UTF-8 (BOMなし) で保存すること。
 * vcxproj に /utf-8 コンパイラフラグが必要。
 * ================================================================ */

/* --- メインループ --- */
#define MSG_TITLE           "=== ENIGMA Compressor ===\n"
#define MSG_HELP_DROP       "ここにファイルをドラッグするか、パスを直接入力してください。\n"
#define MSG_HELP_ENTER      "  [Enter]   = 暗号化 + ログ偽装を実行\n"
#define MSG_HELP_LIST       "  daftar    = キューを表示\n"
#define MSG_HELP_CLEAR      "  bersih    = キューをクリア\n"
#define MSG_HELP_RESTORE    "  pulihkan  = 偽装ログからファイルを復元\n"
#define MSG_HELP_EXIT       "  keluar    = 終了\n\n"
#define MSG_QUEUE_EMPTY     "  (キューは空です)\n"
#define MSG_QUEUE_ENTRY     "  [%d] %s\n"
#define MSG_QUEUE_CLEARED   "  キューをクリアしました。\n"
#define MSG_ADDED           "  追加 [%d]: %s\n"
#define ERR_QUEUE_FULL      "  [エラー] キューが満杯です (最大 %d)。\n"
#define ERR_ALLOC_QUEUE     "  [エラー] パスキューのメモリ確保に失敗しました。\n"

/* --- 暗号化 (gabungkan_berkas) --- */
#define MSG_NO_VALID_FILES  "  (キューに有効なファイルがありません)\n"
#define MSG_PROMPT_BASENAME "出力ベース名 (空白 = output): "
#define MSG_PROMPT_PNG_ENC  "鍵PNGファイル (空白 = %s_key.png): "
#define MSG_PROMPT_PASSWORD "XORパスワード (空白 = XORなし): "
#define MSG_STEP1           "\n[STEP 1/6] シードを取得中...\n"
#define MSG_STEP2           "[STEP 2/6] PNGのLSBにシードを埋め込み中: %s\n"
#define MSG_STEP3           "[STEP 3/6] Enigmaロータを初期化中...\n"
#define MSG_STEP4           "[STEP 4/6] %d 個のファイルをパック中 -> %s\n"
#define MSG_STEP5           "[STEP 5/6] 暗号化中: %s -> %s\n"
#define MSG_STEP6           "[STEP 6/6] 偽装中: %s -> %s_partNNN.log\n"
#define MSG_SEED            "[SEED] %s\n\n"
#define MSG_PNG_OK          "[PNG]   シードを埋め込みました: %s\n\n"
#define MSG_ENIGMA_READY    "[ENIGMA] ロータ準備完了。\n\n"
#define MSG_PACK_DONE       "[PACK]  完了: %s\n\n"
#define MSG_ENC_DONE        "[ENC]   完了: %s\n\n"
#define MSG_LOG_DONE        "[LOG]   完了: %d 分割。\n\n"
#define MSG_DONE_TITLE      "=== 完了 ===\n"
#define MSG_DONE_LOG        "  ログ : %s_part001.log ... _part%03d.log\n"
#define MSG_DONE_KEY        "  鍵   : %s  (大切に保管してください！)\n\n"
#define ERR_ALLOC_FILES     "  [エラー] ファイルリストのメモリ確保に失敗しました。\n"
#define ERR_SEED            "  [エラー] Wikipediaからシードを取得できませんでした。\n\n"
#define ERR_PNG_SAVE        "  [エラー] シードのPNG保存に失敗しました。\n\n"
#define ERR_PACK            "  [エラー] パックに失敗しました。\n\n"
#define ERR_ENC             "  [エラー] 暗号化に失敗しました。\n\n"
#define ERR_LOG             "  [エラー] ログ偽装に失敗しました。\n\n"

/* --- 復元 (pulihkan_berkas) --- */
#define MSG_PROMPT_LOG_PREFIX   "ログの接頭辞を入力 (例: output): "
#define MSG_PROMPT_OUT_ARCHIVE  "出力アーカイブ名 (空白 = hasil.engm): "
#define MSG_PROMPT_PNG_DEC      "鍵PNGファイル (空白 = %s_key.png): "
#define MSG_RESTORE_STEP0       "\n[STEP 0/3] PNGのLSBからシードを抽出中: %s\n"
#define MSG_RESTORE_STEP1       "[STEP 1/3] ログから復元中: %s_partNNN.log -> %s\n"
#define MSG_RESTORE_STEP2       "[STEP 2/3] Enigmaロータを初期化中...\n"
#define MSG_RESTORE_STEP3       "[STEP 3/3] 復号中: %s -> %s\n"
#define MSG_RESTORE_STEP4       "[STEP 4/4] アーカイブを展開中: %s\n"
#define MSG_RESTORE_PNG_OK      "[PNG]  シードを抽出しました。\n\n"
#define MSG_RESTORE_LOG_OK      "[LOG]  %lld バイトを復元しました。\n\n"
#define MSG_RESTORE_DEC_OK      "[DEC]  完了: %s\n\n"
#define MSG_RESTORE_ARCHIVE_COUNT "[アーカイブ] %u 個のファイルが見つかりました。\n"
#define MSG_RESTORE_FILE_OK     "  [OK]  %-60s  %llu バイト\n"
#define MSG_RESTORE_DONE_TITLE  "\n=== 完了 ===\n"
#define MSG_RESTORE_DONE        "  %u 個のファイルを復元しました。\n\n"
#define ERR_PNG_EXTRACT         "  [エラー] PNGからシードの抽出に失敗しました。\n\n"
#define ERR_LOG_RESTORE         "  [エラー] ログの復元に失敗しました。\n\n"
#define ERR_DEC                 "  [エラー] 復号に失敗しました。\n\n"
#define ERR_OPEN_ARCHIVE        "  [エラー] アーカイブを開けません。\n\n"
#define ERR_ALLOC_BUF           "  [エラー] メモリ確保に失敗しました。\n\n"
#define ERR_READ_ARCHIVE        "  [エラー] アーカイブの読み込みに失敗しました。\n\n"
#define ERR_ALLOC_ENTRY         "  [エラー] エントリのメモリ確保に失敗しました。\n\n"
#define ERR_INVALID_ARCHIVE     "  [エラー] アーカイブが無効またはシードが一致しません。\n\n"
#define ERR_SKIP_FILE           "  [SKIP] %s (書き込み用に開けませんでした)\n"
