#pragma once
/* ================================================================
 * lang_id.h  -  String Bahasa Indonesia (string asli)
 * ================================================================ */

/* --- Utama --- */
#define MSG_TITLE           "=== ENIGMA Compressor ===\n"
#define MSG_HELP_DROP       "Seret berkas ke jendela ini atau ketik jalur secara manual.\n"
#define MSG_HELP_ENTER      "  [Enter]   = jalankan enkripsi + penyamaran log\n"
#define MSG_HELP_LIST       "  daftar    = tampilkan antrian\n"
#define MSG_HELP_CLEAR      "  bersih    = kosongkan antrian\n"
#define MSG_HELP_RESTORE    "  pulihkan  = pulihkan berkas dari log tersamar\n"
#define MSG_HELP_EXIT       "  keluar    = tutup program\n\n"
#define MSG_QUEUE_EMPTY     "  (antrian kosong)\n"
#define MSG_QUEUE_ENTRY     "  [%d] %s\n"
#define MSG_QUEUE_CLEARED   "  Antrian dikosongkan.\n"
#define MSG_ADDED           "  Ditambahkan [%d]: %s\n"
#define ERR_QUEUE_FULL      "  [GAGAL] Antrian penuh (maks %d).\n"
#define ERR_ALLOC_QUEUE     "  [GAGAL] Alokasi memori untuk antrian_jalur gagal.\n"

/* --- Enkripsi (gabungkan_berkas) --- */
#define MSG_NO_VALID_FILES  "  (tidak ada berkas valid dalam antrian)\n"
#define MSG_PROMPT_BASENAME "Nama dasar keluaran (kosong = output): "
#define MSG_PROMPT_PNG_ENC  "Nama berkas PNG kunci (kosong = %s_key.png): "
#define MSG_PROMPT_PASSWORD "Sandi XOR (kosong = tanpa XOR): "
#define MSG_STEP1           "\n[STEP 1/6] Sedang memproses benih...\n"
#define MSG_STEP2           "[STEP 2/6] Menyembunyikan benih ke PNG LSB: %s\n"
#define MSG_STEP3           "[STEP 3/6] Inisialisasi rotor Enigma...\n"
#define MSG_STEP4           "[STEP 4/6] Mengemas %d berkas -> %s\n"
#define MSG_STEP5           "[STEP 5/6] Enkripsi: %s -> %s\n"
#define MSG_STEP6           "[STEP 6/6] Menyamarkan: %s -> %s_partNNN.log\n"
#define MSG_SEED            "[SEED] %s\n\n"
#define MSG_PNG_OK          "[PNG]   Benih tersembunyi di: %s\n\n"
#define MSG_ENIGMA_READY    "[ENIGMA] Rotor siap.\n\n"
#define MSG_PACK_DONE       "[PACK]  Selesai: %s\n\n"
#define MSG_ENC_DONE        "[ENC]   Selesai: %s\n\n"
#define MSG_LOG_DONE        "[LOG]   Selesai: %d bagian.\n\n"
#define MSG_DONE_TITLE      "=== SELESAI ===\n"
#define MSG_DONE_LOG        "  Log  : %s_part001.log ... _part%03d.log\n"
#define MSG_DONE_KEY        "  Kunci: %s  (simpan baik-baik!)\n\n"
#define ERR_ALLOC_FILES     "  [GAGAL] Alokasi memori untuk jalur_final gagal.\n"
#define ERR_SEED            "  [GAGAL] Tidak dapat mengambil benih dari Wikipedia.\n\n"
#define ERR_PNG_SAVE        "  [GAGAL] Gagal menyimpan benih ke PNG.\n\n"
#define ERR_PACK            "  [GAGAL] Pengemasan gagal.\n\n"
#define ERR_ENC             "  [GAGAL] Enkripsi gagal.\n\n"
#define ERR_LOG             "  [GAGAL] Penyamaran log gagal.\n\n"

/* --- Pemulihan (pulihkan_berkas) --- */
#define MSG_PROMPT_LOG_PREFIX   "Awalan log masukan (mis. output): "
#define MSG_PROMPT_OUT_ARCHIVE  "Berkas keluaran arsip (kosong = hasil.engm): "
#define MSG_PROMPT_PNG_DEC      "Berkas PNG kunci (kosong = %s_key.png): "
#define MSG_RESTORE_STEP0       "\n[STEP 0/3] Mengekstrak benih dari PNG LSB: %s\n"
#define MSG_RESTORE_STEP1       "[STEP 1/3] Memulihkan dari log: %s_partNNN.log ke %s\n"
#define MSG_RESTORE_STEP2       "[STEP 2/3] Inisialisasi rotor Enigma...\n"
#define MSG_RESTORE_STEP3       "[STEP 3/3] Dekripsi: %s -> %s\n"
#define MSG_RESTORE_STEP4       "[STEP 4/4] Membuka arsip: %s\n"
#define MSG_RESTORE_PNG_OK      "[PNG]  Benih berhasil diekstrak.\n\n"
#define MSG_RESTORE_LOG_OK      "[LOG]  %lld byte dipulihkan.\n\n"
#define MSG_RESTORE_DEC_OK      "[DEC]  Selesai: %s\n\n"
#define MSG_RESTORE_ARCHIVE_COUNT "[ARSIP] %u berkas ditemukan.\n"
#define MSG_RESTORE_FILE_OK     "  [OK]  %-60s  %llu byte\n"
#define MSG_RESTORE_DONE_TITLE  "\n=== SELESAI ===\n"
#define MSG_RESTORE_DONE        "  %u berkas dipulihkan.\n\n"
#define ERR_PNG_EXTRACT         "  [GAGAL] Gagal mengekstrak benih dari PNG.\n\n"
#define ERR_LOG_RESTORE         "  [GAGAL] Pemulihan log gagal.\n\n"
#define ERR_DEC                 "  [GAGAL] Dekripsi gagal.\n\n"
#define ERR_OPEN_ARCHIVE        "  [GAGAL] Tidak dapat membuka arsip.\n\n"
#define ERR_ALLOC_BUF           "  [GAGAL] Alokasi memori gagal.\n\n"
#define ERR_READ_ARCHIVE        "  [GAGAL] Gagal membaca arsip.\n\n"
#define ERR_ALLOC_ENTRY         "  [GAGAL] Alokasi memori untuk entri gagal.\n\n"
#define ERR_INVALID_ARCHIVE     "  [GAGAL] Arsip tidak valid atau benih salah.\n\n"
#define ERR_SKIP_FILE           "  [SKIP] %s (gagal membuka untuk menulis)\n"
